//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ado.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ado.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} could not be launched: {1} ähnelt.
        /// </summary>
        internal static string _0CouldNotBeLaunched1 {
            get {
                return ResourceManager.GetString("_0CouldNotBeLaunched1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Added to PATH:  ähnelt.
        /// </summary>
        internal static string AddedToPATH {
            get {
                return ResourceManager.GetString("AddedToPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   adds it to the user&apos;s PATH variable. ähnelt.
        /// </summary>
        internal static string AddsItToTheUserSPATHVariable {
            get {
                return ResourceManager.GetString("AddsItToTheUserSPATHVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ado - Administrator do, ©2024 - Manfred Mueller ähnelt.
        /// </summary>
        internal static string AdoAdministratorDo2024ManfredMueller {
            get {
                return ResourceManager.GetString("AdoAdministratorDo2024ManfredMueller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Optional command line arguments to prog ähnelt.
        /// </summary>
        internal static string ArgsOptionalCommandLineArgumentsToProg {
            get {
                return ResourceManager.GetString("ArgsOptionalCommandLineArgumentsToProg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Command Line too long ähnelt.
        /// </summary>
        internal static string CommandLineTooLong {
            get {
                return ResourceManager.GetString("CommandLineTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die %COMSPEC% is not defined ähnelt.
        /// </summary>
        internal static string COMSPECIsNotDefined {
            get {
                return ResourceManager.GetString("COMSPECIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creating command line failed ähnelt.
        /// </summary>
        internal static string CreatingCommandLineFailed {
            get {
                return ResourceManager.GetString("CreatingCommandLineFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execute a process on the command line elevated via UAC ähnelt.
        /// </summary>
        internal static string ExecuteAProcessOnTheCommandLineElevatedViaUAC {
            get {
                return ResourceManager.GetString("ExecuteAProcessOnTheCommandLineElevatedViaUAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   executes prog in it (CMD.EXE, etc.) ähnelt.
        /// </summary>
        internal static string ExecutesProgInItCMDEXEEtc {
            get {
                return ResourceManager.GetString("ExecutesProgInItCMDEXEEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation failed:  ähnelt.
        /// </summary>
        internal static string InstallationFailed {
            get {
                return ResourceManager.GetString("InstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Installs the program to current user&apos;s Program Files and ähnelt.
        /// </summary>
        internal static string InstallsTheProgramToCurrentUserSProgramFilesAnd {
            get {
                return ResourceManager.GetString("InstallsTheProgramToCurrentUserSProgramFilesAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid arguments ähnelt.
        /// </summary>
        internal static string InvalidArguments {
            get {
                return ResourceManager.GetString("InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Starts the the %COMSPEC% environment variable value and ähnelt.
        /// </summary>
        internal static string KStartsTheTheCOMSPECEnvironmentVariableValueAnd {
            get {
                return ResourceManager.GetString("KStartsTheTheCOMSPECEnvironmentVariableValueAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program installed successfully. ähnelt.
        /// </summary>
        internal static string ProgramInstalledSuccessfully {
            get {
                return ResourceManager.GetString("ProgramInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program uninstalled successfully. ähnelt.
        /// </summary>
        internal static string ProgramUninstalledSuccessfully {
            get {
                return ResourceManager.GetString("ProgramUninstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - The program to execute ähnelt.
        /// </summary>
        internal static string ProgTheProgramToExecute {
            get {
                return ResourceManager.GetString("ProgTheProgramToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removed from PATH:  ähnelt.
        /// </summary>
        internal static string RemovedFromPATH {
            get {
                return ResourceManager.GetString("RemovedFromPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   removes it from the user&apos;s PATH variable. ähnelt.
        /// </summary>
        internal static string RemovesItFromTheUserSPATHVariable {
            get {
                return ResourceManager.GetString("RemovesItFromTheUserSPATHVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Shows this help ähnelt.
        /// </summary>
        internal static string ShowsThisHelp {
            get {
                return ResourceManager.GetString("ShowsThisHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstallation failed:  ähnelt.
        /// </summary>
        internal static string UninstallationFailed {
            get {
                return ResourceManager.GetString("UninstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Uninstalls the program from current user&apos;s Program Files and ähnelt.
        /// </summary>
        internal static string UninstallsTheProgramFromCurrentUserSProgramFilesAnd {
            get {
                return ResourceManager.GetString("UninstallsTheProgramFromCurrentUserSProgramFilesAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrecognized Flag {0} ähnelt.
        /// </summary>
        internal static string UnrecognizedFlag0 {
            get {
                return ResourceManager.GetString("UnrecognizedFlag0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usage: ado [-?|-wait|-k] prog [args] ähnelt.
        /// </summary>
        internal static string UsageAdoWaitKProgArgs {
            get {
                return ResourceManager.GetString("UsageAdoWaitKProgArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Waits until prog terminates ähnelt.
        /// </summary>
        internal static string WaitWaitsUntilProgTerminates {
            get {
                return ResourceManager.GetString("WaitWaitsUntilProgTerminates", resourceCulture);
            }
        }
    }
}
